"""update table names

Revision ID: 13b180d3fc8b
Revises: e2cc99a8bf9c
Create Date: 2023-06-02 00:44:16.552138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13b180d3fc8b'
down_revision = 'e2cc99a8bf9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestforproposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['sparepart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestforquote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['sparepart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rfqs')
    op.drop_table('rfps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfps',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['sparepart.id'], name='rfps_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rfqs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['sparepart.id'], name='rfqs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('requestforquote')
    op.drop_table('requestforproposal')
    # ### end Alembic commands ###
