"""update table names

Revision ID: 4e6fbe55d5a3
Revises: 78e1bd8cb450
Create Date: 2023-06-02 01:11:36.804163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e6fbe55d5a3'
down_revision = '78e1bd8cb450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='vendor_information')
    op.drop_table('vendor_information')
    op.add_column('purchase_orders', sa.Column('sparepart_id', sa.Integer(), nullable=False))
    op.drop_constraint('purchase_orders_ibfk_1', 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'sparepart', ['sparepart_id'], ['id'])
    op.drop_column('purchase_orders', 'part_id')
    op.add_column('requestforproposal', sa.Column('sparepart_id', sa.Integer(), nullable=False))
    op.drop_constraint('requestforproposal_ibfk_1', 'requestforproposal', type_='foreignkey')
    op.create_foreign_key(None, 'requestforproposal', 'sparepart', ['sparepart_id'], ['id'])
    op.drop_column('requestforproposal', 'part_id')
    op.add_column('suppliers', sa.Column('supplier_name', sa.String(length=100), nullable=False))
    op.add_column('suppliers', sa.Column('ontract_start_date', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('contract_end_date', sa.DateTime(), nullable=True))
    op.drop_column('suppliers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('suppliers', 'contract_end_date')
    op.drop_column('suppliers', 'ontract_start_date')
    op.drop_column('suppliers', 'supplier_name')
    op.add_column('requestforproposal', sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requestforproposal', type_='foreignkey')
    op.create_foreign_key('requestforproposal_ibfk_1', 'requestforproposal', 'sparepart', ['part_id'], ['id'])
    op.drop_column('requestforproposal', 'sparepart_id')
    op.add_column('purchase_orders', sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key('purchase_orders_ibfk_1', 'purchase_orders', 'sparepart', ['part_id'], ['id'])
    op.drop_column('purchase_orders', 'sparepart_id')
    op.create_table('vendor_information',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact_person', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contract_start_date', mysql.DATETIME(), nullable=True),
    sa.Column('contract_end_date', mysql.DATETIME(), nullable=True),
    sa.Column('rate_sheet', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sparepart_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sparepart_id'], ['sparepart.id'], name='vendor_information_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'vendor_information', ['id'], unique=False)
    # ### end Alembic commands ###
