"""update table names

Revision ID: 78e1bd8cb450
Revises: 13b180d3fc8b
Create Date: 2023-06-02 00:52:23.564958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78e1bd8cb450'
down_revision = '13b180d3fc8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'purchase_orders', ['id'])
    op.add_column('purchase_requests', sa.Column('sparepart_id', sa.Integer(), nullable=False))
    op.add_column('purchase_requests', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'purchase_requests', ['id'])
    op.drop_constraint('purchase_requests_ibfk_1', 'purchase_requests', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_requests', 'sparepart', ['sparepart_id'], ['id'])
    op.drop_column('purchase_requests', 'part_id')
    op.add_column('requestforproposal', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'requestforproposal', ['id'])
    op.add_column('requestforquote', sa.Column('sparepart_id', sa.Integer(), nullable=False))
    op.add_column('requestforquote', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'requestforquote', ['id'])
    op.drop_constraint('requestforquote_ibfk_1', 'requestforquote', type_='foreignkey')
    op.create_foreign_key(None, 'requestforquote', 'sparepart', ['sparepart_id'], ['id'])
    op.drop_column('requestforquote', 'part_id')
    op.add_column('sparepart', sa.Column('part_name', sa.String(length=100), nullable=False))
    op.add_column('sparepart', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('sparepart', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'sparepart', ['id'])
    op.drop_column('sparepart', 'name')
    op.drop_column('sparepart', 'last_updated')
    op.add_column('suppliers', sa.Column('sparepart_id', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'suppliers', ['id'])
    op.drop_constraint('suppliers_ibfk_1', 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'sparepart', ['sparepart_id'], ['id'])
    op.drop_column('suppliers', 'part_id')
    op.add_column('vendor_information', sa.Column('sparepart_id', sa.Integer(), nullable=False))
    op.add_column('vendor_information', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('vendor_information', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'vendor_information', ['id'])
    op.drop_constraint('vendor_information_ibfk_1', 'vendor_information', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_information', 'sparepart', ['sparepart_id'], ['id'])
    op.drop_column('vendor_information', 'part_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_information', sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vendor_information', type_='foreignkey')
    op.create_foreign_key('vendor_information_ibfk_1', 'vendor_information', 'sparepart', ['part_id'], ['id'])
    op.drop_constraint(None, 'vendor_information', type_='unique')
    op.drop_column('vendor_information', 'date_updated')
    op.drop_column('vendor_information', 'date_created')
    op.drop_column('vendor_information', 'sparepart_id')
    op.add_column('suppliers', sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key('suppliers_ibfk_1', 'suppliers', 'sparepart', ['part_id'], ['id'])
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'date_updated')
    op.drop_column('suppliers', 'date_created')
    op.drop_column('suppliers', 'sparepart_id')
    op.add_column('sparepart', sa.Column('last_updated', mysql.DATETIME(), nullable=True))
    op.add_column('sparepart', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'sparepart', type_='unique')
    op.drop_column('sparepart', 'date_updated')
    op.drop_column('sparepart', 'date_created')
    op.drop_column('sparepart', 'part_name')
    op.add_column('requestforquote', sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requestforquote', type_='foreignkey')
    op.create_foreign_key('requestforquote_ibfk_1', 'requestforquote', 'sparepart', ['part_id'], ['id'])
    op.drop_constraint(None, 'requestforquote', type_='unique')
    op.drop_column('requestforquote', 'date_updated')
    op.drop_column('requestforquote', 'sparepart_id')
    op.drop_constraint(None, 'requestforproposal', type_='unique')
    op.drop_column('requestforproposal', 'date_updated')
    op.add_column('purchase_requests', sa.Column('part_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.create_foreign_key('purchase_requests_ibfk_1', 'purchase_requests', 'sparepart', ['part_id'], ['id'])
    op.drop_constraint(None, 'purchase_requests', type_='unique')
    op.drop_column('purchase_requests', 'date_updated')
    op.drop_column('purchase_requests', 'sparepart_id')
    op.drop_constraint(None, 'purchase_orders', type_='unique')
    op.drop_column('purchase_orders', 'date_updated')
    op.drop_column('purchase_orders', 'date_created')
    # ### end Alembic commands ###
