"""update table names

Revision ID: 92e6ef2d1dbc
Revises: 4e6fbe55d5a3
Create Date: 2023-06-02 01:27:23.998479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92e6ef2d1dbc'
down_revision = '4e6fbe55d5a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'contract_end_date')
    op.drop_column('suppliers', 'ontract_start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('ontract_start_date', mysql.DATETIME(), nullable=True))
    op.add_column('suppliers', sa.Column('contract_end_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
